### ISSUE TITLE
正常安装，测试报错

### ISSUE THREAD

**Issue by sunxuetao** [huobiapi/Websocket-Python3-demo#6]
AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

**Comment by sunxuetao** [comment]
Traceback (most recent call last):
  File "Websocket-Python3-demo-master/orders-accounts-Python3-demo/demo.py", line 4, in <module>
    import websocket
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\__init__.py", line 23, in <module>
    from ._app import WebSocketApp
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\_app.py", line 36, in <module>
    from ._core import WebSocket, getdefaulttimeout
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\_core.py", line 34, in <module>
    from ._handshake import *
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\_handshake.py", line 30, in <module>
    from ._http import *
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\_http.py", line 31, in <module>
    from ._socket import*
  File "\AppData\Local\Continuum\anaconda3\lib\site-packages\websocket\_socket.py", line 30, in <module>
    from ._ssl_compat import *
AttributeError: module 'websocket._ssl_compat' has no attribute 'ssl'

**Comment by sunxuetao** [comment]
using anaconda3 python env
